// 5247.idl : IDL source for 5247.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (5247.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(8A8BBB5F-EEF5-4B6B-B73F-BAF9C01F7D46),
	version(1.0),
	helpstring("5247 1.0 Type Library")
]
library MY5247Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
